/**
 * ASCyber Client-side Search
 */

document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.getElementById('site-search');
    const searchResults = document.getElementById('search-results');

    if (!searchInput || !searchResults) return;

    // Simulated search index (In the future, this could be loaded from a JSON file generated by a build script)
    const searchIndex = [
        { title: "Home", url: "index.html", description: "ASCyber Homepage - Learn, Build, Secure.", category: "General" },
        { title: "About", url: "about.html", description: "About Anand Singh Cyber and our mission.", category: "General" },
        { title: "Cybersecurity Fundamentals", url: "cybersecurity.html", description: "Master the principles of information security.", category: "Category" },
        { title: "Programming Guides", url: "programming.html", description: "Learn Python, C/C++, and JavaScript.", category: "Category" },
        { title: "Computer Networking", url: "networking.html", description: "Understand the backbone of the internet.", category: "Category" },
        { title: "Linux Mastery", url: "linux.html", description: "From essential commands to system administration.", category: "Category" },
        { title: "What Is the CIA Triad?", url: "article-template.html", description: "A fundamental concept in information security: Confidentiality, Integrity, and Availability.", category: "Article" },
        { title: "TCP vs UDP Explained", url: "#", description: "Understanding the difference between the Transmission Control Protocol and User Datagram Protocol.", category: "Article" },
        { title: "Python for Cybersecurity", url: "#", description: "How to leverage Python scripting to automate security tasks.", category: "Article" },
    ];

    searchInput.addEventListener('input', (e) => {
        const query = e.target.value.toLowerCase().trim();
        searchResults.innerHTML = '';

        if (query.length === 0) {
            searchResults.classList.add('hidden');
            return;
        }

        const results = searchIndex.filter(item => 
            item.title.toLowerCase().includes(query) || 
            item.description.toLowerCase().includes(query) ||
            item.category.toLowerCase().includes(query)
        );

        if (results.length > 0) {
            results.forEach(result => {
                const a = document.createElement('a');
                a.href = result.url;
                a.className = 'search-result-item';
                a.innerHTML = `
                    <h4>${result.title}</h4>
                    <p>${result.description}</p>
                `;
                searchResults.appendChild(a);
            });
        } else {
            searchResults.innerHTML = `<div class="no-results">No results found for "${query}"</div>`;
        }

        searchResults.classList.remove('hidden');
    });

    // Hide dropdown when clicking outside
    document.addEventListener('click', (e) => {
        if (!searchInput.contains(e.target) && !searchResults.contains(e.target)) {
            searchResults.classList.add('hidden');
        }
    });
});
